config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

devise_scope :user do
  get '/logout', to: 'devise/sessions#destroy', as: :logout
end



  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }

  namespace :admin do
    resources :genres, except: [:new, :show]
    resources :user_datas, only: [:index, :show, :update]
  end


  resources :users, only: [:show, :edit, :update] do
    get 'timeline', to: 'users#timeline'
    resource :relationships, only: [:create, :destroy]
      get 'index', to: 'relationships#index'
  end

  resources :movies, except: [:index, :edit, :update] do
    resources :goods, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]

  root 'homes#top'
  get 'search', to: 'search#search'
  get 'form', to: 'search#form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id]) #フォローをする
    @user = User.find(params[:user_id])
    @user.create_notification_follow!(current_user) #通知
    redirect_to request.referer #遷移元へ
  end

  def destroy
    current_user.unfollow(params[:user_id]) #フォローを外す
    redirect_to request.referer #遷移元へ
  end

  def index #フォロー・フォロワー一覧
    @user = User.find(params[:user_id])
    @followings = @user.followings
    @followers = @user.followers
    @genres = Genre.all
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_index.html.erb
<% if users.exists? %>
  <div class="row">
    <% users.each do |user| %>
      <div class="card">
        <div class="row my-1 mx-1">
          <div class="col-2">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg',fallback: "no_image.png", class:"image text-left" %>
            <% end %>
          </div>

          <div class="col-6">
            <%= link_to user_path(user), class:"link" do %>
              <%= user.name %>さん</br>
            <% end %>

            <%= user.introduction %>
          </div>

          <div class="col text-right mt-1">
            <% unless user.id == current_user.id %> <!--ログインユーザーが自分のことをフォローできないようにボタンを非表示にする-->
              <% if current_user.following?(user) %>
                <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class:"relationship_action btn btn-light" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"relationship_action btn btn-outline-light" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="none mt-5">ユーザーはいません。</div>
<% end %>

app/views/relationships/index.html.erb
<div class="col-7">
  <div class="row">
    <div class="col-1 mt-1">
      <%= link_to "", user_path(@user), class:"fas fa-arrow-left" %>
    </div>

    <div class="col-11">
      <h3><%= @user.name %></h3>
    </div>
  </div>

  <ul class="nav nav-tabs nav-justified mt-5" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="followings-tab" data-toggle="tab" href="#followings" role="tab" aria-controls="followings" aria-selected="true">フォロー中</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="followers-tab" data-toggle="tab" href="#followers" role="tab" aria-controls="followers" aria-selected="false">フォロワー</a>
    </li>
  </ul>
  <div class="tab-content mt-5" id="myTabContent">
    <div class="tab-pane fade show active" id="followings" role="tabpanel" aria-labelledby="followings-tab">
      <%= render 'relationships/index', users: @followings %>
    </div>
    <div class="tab-pane fade" id="followers" role="tabpanel" aria-labelledby="followers-tab">
      <%= render 'relationships/index', users: @followers %>
    </div>
  </div>
</div>

<div class="col-2 d-none d-lg-block"> <!--md（横幅992px）未満で削除（サイドバーからアクセス可能）-->
  <%= render 'search/search', genres: @genres %>
</div>