config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

devise_scope :user do
  get '/logout', to: 'devise/sessions#destroy', as: :logout
end



  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }

  namespace :admin do
    resources :genres, except: [:new, :show]
    resources :user_datas, only: [:index, :show, :update]
  end


  resources :users, only: [:show, :edit, :update] do
    get 'timeline', to: 'users#timeline'
    resource :relationships, only: [:create, :destroy]
      get 'index', to: 'relationships#index'
  end

  resources :movies, except: [:index, :edit, :update] do
    resources :goods, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]

  root 'homes#top'
  get 'search', to: 'search#search'
  get 'form', to: 'search#form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :movies, dependent: :destroy

#--good機能--
  has_many :goods, dependent: :destroy
  has_many :good_movies, through: :goods, source: :movie

#--フォロー・フォロワー機能--
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

#--通知機能--
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def already_good?(movie)
    self.goods.exists?(movie_id: movie.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def active?
    user_status == true
  end

  validates :name,presence:true


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.order(created_at: :desc) #ユーザーの投稿一覧（新しい順）
    @genres = Genre.all
    @good = Good.new
    goods = Good.where(user_id: @user.id).pluck(:movie_id) #ユーザーがgoodした投稿一覧
    @good_movies = Movie.find(goods)
  end

  def timeline
    @movies = Movie.where(user_id: [current_user.id, *current_user.following_ids]).order(created_at: :desc) #フォローしているユーザーと自分の投稿を新しい順で表示
    @good = Good.new
    @genres = Genre.all
  end

  def edit #ユーザー情報編集
    @user = User.find(params[:id])
    @genres = Genre.all
  end

  def update #ユーザー情報編集
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(@user)
    else
       @genres = Genre.all
       redirect_to edit_user_path, alert: "名前は必須です。"
    end
  end

  def check_login
    redirect_to logout_path if current_user && current_user.user_status != 'active'
  end

  private
  def user_params
  	  params.require(:user).permit(:name, :introduction, :favorite_movie, :profile_image, :user_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<div class="row mt-3">
  <table class="table table-borderless">

    <tr>
      <td><%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg',fallback: "no_image.png", class:"image" %></td>
      <td>
        <% if user.id == current_user.id %>
          <%= link_to "プロフィールを編集", edit_user_path(user.id), class:"user_aaction btn btn-light my-1" %>
        <% else %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class:"user_aaction btn btn-light my-1" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"user_aaction btn btn-outline-light my-1" %>
          <% end %>
        <% end %>
      </td>
    </tr>

    <tr>
      <td>自己紹介</td>
      <td><%= user.introduction %></td>
    </tr>

    <tr>
      <td>好きな映画</td>
      <td><%= user.favorite_movie %></td>
    </tr>

    <tr>
      <td><%= link_to user.followings.count, user_index_path(user.id), class:"link" %>フォロー</td>

      <td><%= link_to user.followers.count, user_index_path(user.id), class:"link" %>フォロワー</td>
    </tr>

  </table>
</div>

<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">投稿一覧</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">GOODS</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <%= render 'movies/index', movies: @movies %>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <%= render 'movies/good_movies', good_movies: @good_movies %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-7">
  <div class="row">
    <div class="col-1 mt-1">
      <%= link_to "", :back, class:"fas fa-arrow-left" %>
    </div>

    <div class="col-11">
      <h3>
        プロフィール変更
      </h3>
    </div>
  </div>

  <span class="text-danger"><%= alert %></span>

  <%= form_with model: @user, local:true do |f| %>
	<div class="row justify-content-center mt-5">
	  <div class="col-11">

      <div class="form-group row">
        <%= f.label :アイコン, class: "col-sm-4 mt-1" %>
        <%= f.attachment_field :profile_image %>
      </div>

      <div class="form-group row">
        <%= f.label :名前, class: "col-sm-4 mt-1" %>
        <%= f.text_field :name, class: "form-control col-sm-8" %>
      </div>

      <div class="form-group row">
        <%= f.label :自己紹介, class: "col-sm-4 mt-4" %>
        <%= f.text_area :introduction, class: "form-control col-sm-8 mt-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :イチオシ映画, class: "col-sm-4 mt-4" %>
        <%= f.text_field :favorite_movie, class: "form-control col-sm-8 mt-3" %>
      </div>

      <div class="text-right mt-5">
        <%= link_to "戻る", user_path(@user.id), class: "btn  btn-success my-1" %>
        <%= f.submit :保存, class: "btn btn-success" %>
      </div>

	  </div>
	</div>
	<% end %>
</div>

<div class="col-2 d-none d-lg-block"> <!--md（横幅992px）未満で削除（サイドバーからアクセス可能）-->
  <%= render 'search/search', genres: @genres %>
</div>

app/views/users/show.html.erb
<div class="col-7">
  <h3><%= @user.name %></h3>
　<%= render 'users/userinfo', user: @user %>
</div>

<div class="col-2 d-none d-lg-block"> <!--md（横幅992px）未満で削除（サイドバーからアクセス可能）-->
  <%= render 'search/search', genres: @genres %>
</div>

app/views/users/timeline.html.erb
<div class="col-7">
  <h3>タイムライン</h3>
  <%= render 'movies/index', movies: @movies %>
</div>

<div class="col-2 d-none d-lg-block"> <!--md（横幅992px）未満で削除（サイドバーからアクセス可能）-->
  <%= render 'search/search', genres: @genres %>
</div>