config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

devise_scope :user do
  get '/logout', to: 'devise/sessions#destroy', as: :logout
end



  devise_for :admin, skip: [:registrations], controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
  }

  namespace :admin do
    resources :genres, except: [:new, :show]
    resources :user_datas, only: [:index, :show, :update]
  end


  resources :users, only: [:show, :edit, :update] do
    get 'timeline', to: 'users#timeline'
    resource :relationships, only: [:create, :destroy]
      get 'index', to: 'relationships#index'
  end

  resources :movies, except: [:index, :edit, :update] do
    resources :goods, only: [:create, :destroy]
  end

  resources :notifications, only: [:index]

  root 'homes#top'
  get 'search', to: 'search#search'
  get 'form', to: 'search#form'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates_uniqueness_of :movie_id, scope: :user_id #ひとつの投稿に対してひとつしかgoodできない
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :goods, dependent: :destroy
  has_many :good_users, through: :goods, source: :user
  has_many :notifications, dependent: :destroy

#--いいねされた時の通知--
  def create_notification_good!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and movie_id = ? and action = ? ", current_user.id, user_id, id, 'good'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        movie_id: id,
        visited_id: user_id,
        action: 'good'
      )
      # 自分の投稿に対し自分でいいねしたの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

#--フォローされた時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  validates :name,presence:true
  validates :rate,presence:true
  validates :genre_id,presence:true
  validates :review,presence:true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }   #作成日時の降順で表示させるようにする（常に新しい通知からデータを取得）
  belongs_to :movie, optional: true
  belongs_to :visitor, class_name: "User", foreign_key: "visitor_id", optional: true
  belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :movies, dependent: :destroy

#--good機能--
  has_many :goods, dependent: :destroy
  has_many :good_movies, through: :goods, source: :movie

#--フォロー・フォロワー機能--
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

#--通知機能--
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def already_good?(movie)
    self.goods.exists?(movie_id: movie.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def active?
    user_status == true
  end

  validates :name,presence:true


end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :authenticate_user!

  def create
    @good = current_user.goods.create(movie_id: params[:movie_id])
    @movie = Movie.find(params[:movie_id])
    @movie.create_notification_good!(current_user) #通知
  end

  def destroy
    @good = Good.find(params[:id])
    @movie = Movie.find(params[:movie_id])
    @good.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @movies = Movie.all.order(created_at: :desc) #新しい順
    @genres = Genre.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.order(created_at: :desc) #ユーザーの投稿一覧（新しい順）
    @genres = Genre.all
    @good = Good.new
    goods = Good.where(user_id: @user.id).pluck(:movie_id) #ユーザーがgoodした投稿一覧
    @good_movies = Movie.find(goods)
  end

  def timeline
    @movies = Movie.where(user_id: [current_user.id, *current_user.following_ids]).order(created_at: :desc) #フォローしているユーザーと自分の投稿を新しい順で表示
    @good = Good.new
    @genres = Genre.all
  end

  def edit #ユーザー情報編集
    @user = User.find(params[:id])
    @genres = Genre.all
  end

  def update #ユーザー情報編集
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(@user)
    else
       @genres = Genre.all
       redirect_to edit_user_path, alert: "名前は必須です。"
    end
  end

  def check_login
    redirect_to logout_path if current_user && current_user.user_status != 'active'
  end

  private
  def user_params
  	  params.require(:user).permit(:name, :introduction, :favorite_movie, :profile_image, :user_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    @visitor = notification.visitor
    case notification.action
    when 'follow'
      tag.a(notification.visitor.name, href: user_path(@visitor)) + '　があなたをフォローしました'
    when 'good'
      tag.a(notification.visitor.name, href: user_path(@visitor)) + '　があなたの投稿にいいねしました'
    end
  end

  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_datas_helper.rb
module UserDatasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<% if request.fullpath.include? "admin"  %>
  <nav class="navbar navbar-expand-lg" >
    <div class="container">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
        <li class="navbar-toggler-icon"></li>
      </button>

      <%= link_to "Movies", admin_genres_path, class: "navbar-brand" %>
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

<% else %>

  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <%= link_to "Movies", root_path, class:"navbar-brand" %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
        <li class="navbar-toggler-icon"></li>
      </button>

      <div class="navbar-collapse collapse show" id="navbarNavDropdown">
        <ul class = "navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "", user_path(current_user.id), class:" far fa-user nav-link text-light" %>
            </li>

            <li class="nav-item">
              <%= link_to "", notifications_path(current_user.id), class:" far fa-bell nav-link text-light" %>
            </li>

            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link text-light" %>
            </li>

          <% else %>
            <li class="nav-item">
             <%= link_to "トップ",root_path, class:"fas nav-link text-light" %>
            </li>

            <li class="nav-item">
              <%= link_to "アカウント作成", new_user_registration_path, class:"nav-link text-light" %>
            </li>

            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class:"nav-link text-light" %>
            </li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/_sidebar.html.erb
<% if request.fullpath.include? "admin"  %>

  <ul class="nav flex-colum">
    <h3>Movies</h3>
    <% if admin_signed_in? %>
      <li class="sidebar-item mt-5">
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
      </li>

      <li class="sidebar-item">
        <%= link_to "ユーザー一覧", admin_user_datas_path, class: "nav-link" %>
      </li>

      <li class="sidebar-item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% end %>
  </ul>

<% else %>

  <ul class = "nav sticky-top d-flex flex-column">
    <% if user_signed_in? %>
      <h3><%= link_to "Movies", root_path, class:"brand link" %></h3>

      <li class="sidebar-item mt-5">
        <%= link_to "　タイムライン", user_timeline_path(current_user.id), class:"nav-link fas fa-home" %> <!--タイムライン-->
      </li>

      <li class="sidebar-item">
        <%= link_to "　プロフィール", user_path(current_user.id), class:"nav-link far fa-user" %> <!--プロフィール-->
      </li>

      <li class="sidebar-item">
        <%= link_to "　通知", notifications_path(current_user.id), class:"nav-link far fa-bell" %> <!--通知-->
        <% if unchecked_notifications.any? %>
          <i class="circle fa fa-circle"></i>
        <% end %>

      </li>

      <li class="sidebar-item">
        <%= link_to "　新規投稿", new_movie_path(current_user.id), class:"nav-link fas fa-pencil-alt" %> <!--新規投稿-->
      </li>

      <li class="sidebar-item">
        <%= link_to "　ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "本当ログアウトしますか？"}, class:"nav-link fas fa-sign-out-alt" %> <!--ログアウト-->
      </li>
    <% else %>
      <h3><%= link_to "Movies", root_path, class:"brand link" %></h3>

      <li class="sidebar-item mt-5">
        <%= link_to "　アカウント作成", new_user_registration_path, class:"nav-link fas fa-user-plus" %>
      </li>

      <li class="sidebar-item">
        <%= link_to "　ログイン", new_user_session_path, class:"nav-link fas fa-sign-in-alt" %>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/layouts/_sidebar_min.html.erb
<% if request.fullpath.include? "admin"  %>

  <ul class="nav flex-colum">
    <h3>Movies</h3>
    <% if admin_signed_in? %>
      <li class="nav-item mt-5">
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
      </li>

      <li class="sidebar-item">
        <%= link_to "ユーザー一覧", admin_user_datas_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% end %>
  </ul>

<% else %>

  <h3><%= link_to "Movies", root_path, class:"brand link" %></h3>
  <ul class = "nav mt-5 d-flex flex-column">
    <% if user_signed_in? %>
      <li class="sidebar-min-item">
        <%= link_to "", form_path(current_user.id), class:"fas fa-search nav-link" %> <!--検索-->
      </li>

      <li class="sidebar-min-item">
        <%= link_to "", user_timeline_path(current_user.id), class:"fas fa-home nav-link text-light" %> <!--タイムライン-->
      </li>

      <li class="sidebar-min-item">
        <%= link_to "", user_path(current_user.id), class:"far fa-user nav-link text-light" %> <!--プロフィール-->
      </li>

      <li class="sidebar-min-item">
        <%= link_to "", notifications_path(current_user.id), class:"far fa-bell nav-link text-light" %> <!--通知-->
      </li>

      <li class="sidebar-min-item">
        <%= link_to "", new_movie_path(current_user.id), class:"fas fa-pencil-alt nav-link text-light" %> <!--新規投稿-->
      </li>

      <li class="sidebar-min-item">
        <%= link_to "", destroy_user_session_path, method: :delete, data: {confirm: "本当ログアウトしますか？"}, class:"fas fa-sign-out-alt nav-link text-light" %> <!--ログアウト-->
      </li>

    <% else %>
      <li class="nav-item">
       <%= link_to "トップ",root_path, class:"fas nav-link text-light" %>
      </li>

      <li class="nav-item">
        <%= link_to "", new_user_registration_path, class:"nav-link fas fa-user-plus" %>
      </li>

      <li class="nav-item">
        <%= link_to "", new_user_session_path, class:"nav-link fas fa-sign-in-alt" %>
      </li>

    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a9c6483f70.js" crossorigin="anonymous"></script> <!--Font Awesome-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container-fluid mt-5" >
      <div class="row justify-content-center">
        <div class="sidebar col-3 d-none d-lg-block"> <!--md（横幅992px）以上時のサイドバー-->
          <%= render 'layouts/sidebar' %>
        </div>

        <div class="sidebar col-2 d-block d-lg-none"> <!--md（横幅992px）未満時のサイドバー-->
          <%= render 'layouts/sidebar_min', genres: @genres %>
        </div>

        <%= yield %>

      </div>
    </div>


  </body>
</html>